CREATE TABLE Pesquisa (
    PesquisaId BIGINT IDENTITY(1,1) PRIMARY KEY,
    ResidenciaId BIGINT NOT NULL,
    DataDaVisita DATE NOT NULL,
    Pendencia INT NOT NULL,
    NomeDoMorador NVARCHAR(255) NOT NULL,
    NumeroDeHabitantes INT NOT NULL,
    TipoDeParede INT NOT NULL,
    OutraParede NVARCHAR(255) NULL,
    TipoDeTeto INT NOT NULL,
    OutroTeto NVARCHAR(255) NULL,
    CapturaIntra BIT NOT NULL,
    CapturaPeri BIT NOT NULL,
    AnexosPositivos INT NOT NULL,
    AnexosNegativos INT NOT NULL,
    NumeroDeGatos INT NOT NULL,
    NumeroDeCachorros INT NOT NULL,
    DataDeRegistro DATETIME NOT NULL,
    DataDeAtualizacao DATETIME NOT NULL,
    CriadoPor BIGINT NOT NULL,
    AtualizadoPor BIGINT NOT NULL,
    CONSTRAINT FK_Pesquisa_Residencia FOREIGN KEY (ResidenciaId) REFERENCES Residencia(ResidenciaId)
);