version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - sigen-network

  frontend:
    build:
      context: ./sigen-frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - sigen-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Complex@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - sigen-network

networks:
  sigen-network:
    driver: bridge