version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  frontend:
    build:
      context: ./sigen-frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "1029384756"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"