# Usar uma imagem base do Node.js
FROM node:18 AS base

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos de configuração
COPY package.json package-lock.json ./

# Instalar dependências
RUN npm install

# Copiar o restante dos arquivos
COPY . .

# Compilar o projeto
RUN npm rebuild lightningcss || true
RUN npm install --force
RUN npm run build || exit 0

# Etapa de produção
FROM node:18 AS development
WORKDIR /app
COPY --from=base /app .
CMD ["npm", "start"]