# Etapa de build
FROM node:20-bullseye as build

WORKDIR /app

# Copia os arquivos e instala dependências
COPY package*.json ./
RUN npm install

COPY . .

# Compila o projeto
RUN npm run build

# Etapa de produção
FROM node:20-bullseye as runtime

WORKDIR /app

COPY --from=build /app ./

EXPOSE 3000
CMD ["npm", "start"]
